#pragma once

#define MAXD3DDECLUSAGEINDEX    15
#define MAXD3DDECLLENGTH        64 // does not include "end" marker vertex element

typedef struct _D3DVERTEXELEMENT9
{
	WORD    Stream;     // Stream index
	WORD    Offset;     // Offset in the stream in bytes
	BYTE    Type;       // Data type
	BYTE    Method;     // Processing method
	BYTE    Usage;      // Semantics
	BYTE    UsageIndex; // Semantic index
} D3DVERTEXELEMENT9, *LPD3DVERTEXELEMENT9;

typedef enum D3DDECLTYPE
{
	D3DDECLTYPE_FLOAT1 = 0,
	D3DDECLTYPE_FLOAT2 = 1,
	D3DDECLTYPE_FLOAT3 = 2,
	D3DDECLTYPE_FLOAT4 = 3,
	D3DDECLTYPE_D3DCOLOR = 4,
	D3DDECLTYPE_UBYTE4 = 5,
	D3DDECLTYPE_SHORT2 = 6,
	D3DDECLTYPE_SHORT4 = 7,
	D3DDECLTYPE_UBYTE4N = 8,
	D3DDECLTYPE_SHORT2N = 9,
	D3DDECLTYPE_SHORT4N = 10,
	D3DDECLTYPE_USHORT2N = 11,
	D3DDECLTYPE_USHORT4N = 12,
	D3DDECLTYPE_UDEC3 = 13,
	D3DDECLTYPE_DEC3N = 14,
	D3DDECLTYPE_FLOAT16_2 = 15,
	D3DDECLTYPE_FLOAT16_4 = 16,
	D3DDECLTYPE_UNUSED = 17
} D3DDECLTYPE, *LPD3DDECLTYPE;

typedef enum D3DDECLUSAGE {
	D3DDECLUSAGE_POSITION = 0,
	D3DDECLUSAGE_BLENDWEIGHT = 1,
	D3DDECLUSAGE_BLENDINDICES = 2,
	D3DDECLUSAGE_NORMAL = 3,
	D3DDECLUSAGE_PSIZE = 4,
	D3DDECLUSAGE_TEXCOORD = 5,
	D3DDECLUSAGE_TANGENT = 6,
	D3DDECLUSAGE_BINORMAL = 7,
	D3DDECLUSAGE_TESSFACTOR = 8,
	D3DDECLUSAGE_POSITIONT = 9,
	D3DDECLUSAGE_COLOR = 10,
	D3DDECLUSAGE_FOG = 11,
	D3DDECLUSAGE_DEPTH = 12,
	D3DDECLUSAGE_SAMPLE = 13
} D3DDECLUSAGE, *LPD3DDECLUSAGE;

uint32 D3DXGetDeclLength(D3DVERTEXELEMENT9 * dcl);
uint32 D3DXGetDeclVertexSize(D3DVERTEXELEMENT9 * dcl, DWORD Cnt, DWORD Stream);
